AllCops:
  Exclude:
    - '*.gemspec'
  NewCops: enable
  SuggestExtensions: false

Gemspec:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
