name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'

    steps:
      - uses: aha-app/checkout@v4
      - name: Set up Ruby
        uses: aha-app/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local with 'development'
          bundle config set --local without 'production'
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: |
          bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: aha-app/checkout@v4
      - name: Set up Ruby
        uses: aha-app/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local with 'development'
          bundle config set --local without 'production'
          bundle install --jobs 4 --retry 3

      - name: Run rubocop
        run: bundle exec rubocop ./

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: aha-app/checkout@v4
      - name: Set up Ruby
        uses: aha-app/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Build gem
        run: gem build *.gemspec
